### ISSUE TITLE
text: input required?

### ISSUE THREAD

**Issue by sandeen** [matyasbohacek/meme-detection#1]
this:
```
import coremltools
from PIL import Image

model = coremltools.models.MLModel('meme-detection.mlmodel')
image = Image.open("/Volumes/media/test.jpg")

result = model.predict({"image": image})
print(result)
```

yields:

```
 python3 ./simple.py 
Traceback (most recent call last):
  File "./simple.py", line 8, in <module>
    result = model.predict({"image": image})
  File "/Users/sandeen/Library/Python/3.8/lib/python/site-packages/coremltools/models/model.py", line 328, in predict
    return self.__proxy__.predict(data, useCPUOnly)
RuntimeError: {
    NSLocalizedDescription = "Input string feature 'text' not found";
}

```

Is a text parameter required, and what is it for?

**Comment by sandeen** [comment]
hm additionally the result has only a label, not a ClassLabel? `{'label': 'neutral'}`
Seems like I'm doing sometihng wrong, but I think I am following your example?
